### ISSUE TITLE
Portal My Videos Tab Update

### ISSUE THREAD

**Issue by glouleon** [glouleon/pinper.com-post-launch#12]
For this page: http://pinper.com/portal/my-videos
We need to change the big bold text that says "You have no video uploads" 

To instead say:
Virtual Coaching services have not been provided

Then: Move the Virtual Coach Videos drop down below this section. So it is AFTER the Request / purchase buttons on the pages for those that DO NOT have vcoach credits

and then When they have uploaded their videos, it should go AFTER The Workshop Videos Drop down.

<img width="932" alt="screenshot 2015-07-20 15 46 06" src="https://cloud.githubusercontent.com/assets/11607092/8786938/c3890a9c-2ef6-11e5-9126-2ba4d56b1131.png">
<img width="957" alt="screenshot 2015-07-20 15 45 17" src="https://cloud.githubusercontent.com/assets/11607092/8786937/c387b62e-2ef6-11e5-952a-640b19a0c0ad.png">

**Comment by ghost** [comment]
Hi Gerri,
I committed the changes to the server, please check if it works for you now.

**Comment by glouleon** [comment]
The site is messed up. Check it on your side

Gerri Leon
VP Marketing and Operations
Pinnacle Performance Company
619-200-2659

On Jul 26, 2015, at 7:11 AM, Romel John Santos <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Gerri,
I committed the changes to the server, please check if it works for you now.
